"""User profile, deltas, sessions (Dev A). FROZEN paths — design §11.6/§11.9."""
from __future__ import annotations

from fastapi import APIRouter, HTTPException, Request

from core.logging import get_logger
from models.agent import ConfirmDeltaRequest
from models.preference import UserProfilePublic
from routes.stub_helpers import not_implemented
from services.preference_confirm_service import preference_confirm_service

logger = get_logger(__name__)

router = APIRouter(prefix="/api/v1/users", tags=["user"])

# Profile fields a user may explicitly confirm/reject (design §11.6, phase-04 F3).
# Bounds WHAT gets mutated, not WHO — see the AUTH TODO on the delta routes below.
_PROFILE_FIELD_WHITELIST: frozenset[str] = frozenset(
    {
        "liked_cuisines",
        "disliked_cuisines",
        "spice_tolerance",
        "dietary",
        "budget_level",
        "distance_preference_km",
    }
)
_VALID_OPERATIONS: frozenset[str] = frozenset({"set", "add", "remove"})


def _validate_delta(body: ConfirmDeltaRequest) -> None:
    """Reject malformed deltas early with a 400: operation must be set/add/remove and
    field must be in the profile whitelist. The repo re-validates the value shape per
    field (list[str] / enum+membership / float range) — this guard bounds the field name
    so an attacker cannot target arbitrary columns (e.g. updated_at / PK)."""
    if body.operation not in _VALID_OPERATIONS:
        raise HTTPException(
            status_code=400,
            detail=(
                f"operation must be one of {sorted(_VALID_OPERATIONS)} "
                f"(got {body.operation!r})"
            ),
        )
    if body.field not in _PROFILE_FIELD_WHITELIST:
        raise HTTPException(
            status_code=400,
            detail=f"field not allowed: {body.field!r}",
        )


@router.get("/{user_id}/profile")
def get_user_profile(user_id: str) -> object:
    return not_implemented(f"GET /api/v1/users/{user_id}/profile")


@router.post(
    "/{user_id}/profile/deltas/{delta_id}/confirm",
    response_model=UserProfilePublic,
)
def confirm_delta(
    user_id: str,
    delta_id: str,
    body: ConfirmDeltaRequest,
    request: Request,
) -> UserProfilePublic:
    """Apply a proposed profile delta after explicit user confirmation (UC §11.6).

    Proposals are EPHEMERAL — `delta_id` is generated by `preference_service` and never
    stored server-side, so the FE re-sends the delta body {field, operation, value} and
    the path `delta_id` is used only as an idempotency/correlation key (persisted in the
    event's `evidence_refs`). The service owns one DB tx: idempotent via
    `find_by_evidence(delta_id, "confirmed")`, upserts `user_profiles`, then appends a
    `preference_events` audit row (status=confirmed, scope=confirmed_global)."""
    _validate_delta(body)
    client_ip = request.client.host if request.client else "unknown"
    logger.info(
        "preference_confirm user_id=%s delta_id=%s op=%s field=%s ip=%s",
        user_id,
        delta_id,
        body.operation,
        body.field,
        client_ip,
    )
    # P1 TODO(AUTH): assert path user_id == authenticated principal before apply_delta
    # (IDOR). Currently path-only trust; gate behind real auth in prod. Without a real
    # auth principal, anyone POSTing a user_id + fabricated delta_id mutates that user's
    # profile. The field whitelist bounds WHAT, not WHO.
    return preference_confirm_service.confirm(user_id, delta_id, body)


@router.post("/{user_id}/profile/deltas/{delta_id}/reject")
def reject_delta(
    user_id: str,
    delta_id: str,
    request: Request,
    body: ConfirmDeltaRequest | None = None,
) -> dict[str, bool]:
    """Record an explicit rejection of a proposed delta (UC §11.6).

    No profile mutation; appends a `preference_events` audit row (status=rejected). ``body``
    is optional — the FE ``rejectDelta`` posts no body (the path carries user_id + delta_id);
    field/op are then logged as ``<none>``. When a body IS sent it is validated like confirm."""
    if body is not None:
        _validate_delta(body)
    client_ip = request.client.host if request.client else "unknown"
    logger.info(
        "preference_reject user_id=%s delta_id=%s op=%s field=%s ip=%s",
        user_id,
        delta_id,
        getattr(body, "operation", "<none>"),
        getattr(body, "field", "<none>"),
        client_ip,
    )
    # P1 TODO(AUTH): assert path user_id == authenticated principal (IDOR) — see confirm_delta.
    preference_confirm_service.reject(user_id, delta_id, body)
    return {"ok": True}


@router.delete("/{user_id}/preferences/{field}")
def delete_preference(user_id: str, field: str) -> object:
    return not_implemented(f"DELETE /api/v1/users/{{user_id}}/preferences/{field}")


@router.get("/{user_id}/sessions")
def list_sessions(user_id: str) -> object:
    return not_implemented(f"GET /api/v1/users/{user_id}/sessions")
