"""User profile, deltas, sessions (Dev A). FROZEN paths — design §11.6/§11.9.

phase-01: GET /profile + PATCH /profile un-stubbed (canonical taste profile read/write).
Confirm/reject/PATCH are IDOR-guarded (require_dev_only) until real auth lands.
"""
from __future__ import annotations

from fastapi import APIRouter, Depends, HTTPException, Request
from pydantic import BaseModel
from sqlalchemy.exc import IntegrityError

from core.dependencies import require_dev_only
from core.logging import get_logger
from models.agent import ConfirmDeltaRequest, ProfilePatchRequest
from models.preference import UserProfilePublic
from routes.stub_helpers import not_implemented
from services.liked_merchant_service import liked_merchant_service
from services.preference_confirm_service import preference_confirm_service
from services.user_profile_service import user_profile_service

logger = get_logger(__name__)

router = APIRouter(prefix="/api/v1/users", tags=["user"])

# Profile fields a user may explicitly confirm/reject (design §11.6, phase-04 F3).
# Bounds WHAT gets mutated, not WHO — the IDOR guard + (future) auth gate WHO.
_PROFILE_FIELD_WHITELIST: frozenset[str] = frozenset(
    {
        "liked_cuisines",
        "disliked_cuisines",
        "spice_tolerance",
        "dietary",
        "budget_level",
        "distance_preference_km",
    }
)
_VALID_OPERATIONS: frozenset[str] = frozenset({"set", "add", "remove"})


def _validate_delta(body: ConfirmDeltaRequest) -> None:
    """Reject malformed deltas early with a 400: operation must be set/add/remove and
    field must be in the profile whitelist. The repo re-validates the value shape per
    field (list[str] / enum+membership / float range) — this guard bounds the field name
    so an attacker cannot target arbitrary columns (e.g. updated_at / PK)."""
    if body.operation not in _VALID_OPERATIONS:
        raise HTTPException(
            status_code=400,
            detail=(
                f"operation must be one of {sorted(_VALID_OPERATIONS)} "
                f"(got {body.operation!r})"
            ),
        )
    if body.field not in _PROFILE_FIELD_WHITELIST:
        raise HTTPException(
            status_code=400,
            detail=f"field not allowed: {body.field!r}",
        )


@router.get("/{user_id}/profile", response_model=UserProfilePublic)
def get_user_profile(user_id: str) -> UserProfilePublic:
    """Return the user's confirmed preference profile (§6.5). 404 when absent.

    Read-only — not IDOR-guarded (taste prefs carry no PII; the FE loads its own user_id).
    The ``get_user_profile`` CrewAI tool reads the same row."""
    return user_profile_service.get_profile(user_id)


@router.patch("/{user_id}/profile", response_model=UserProfilePublic)
def update_profile(
    user_id: str,
    body: ProfilePatchRequest,
    request: Request,
    _guard: bool = Depends(require_dev_only),
) -> UserProfilePublic:
    """Explicit user edit of the taste profile (§11.6).

    Partial update — only fields in the body are applied (list fields replace). One tx:
    atomic B5 validation + apply + audit (source=user_edit). IDOR-guarded (dev-only until
    auth — see require_dev_only)."""
    patch = body.changed_fields()
    if not patch:
        raise HTTPException(status_code=400, detail="No taste-profile fields to update.")
    client_ip = request.client.host if request.client else "unknown"
    logger.info(
        "profile_patch user_id=%s fields=%s ip=%s",
        user_id,
        sorted(patch),
        client_ip,
    )
    # TODO(AUTH): assert path user_id == authenticated principal (IDOR). require_dev_only
    # blocks production until then; replace this guard with a real auth dependency.
    return user_profile_service.update_profile(user_id, patch)


@router.post(
    "/{user_id}/profile/deltas/{delta_id}/confirm",
    response_model=UserProfilePublic,
)
def confirm_delta(
    user_id: str,
    delta_id: str,
    body: ConfirmDeltaRequest,
    request: Request,
    _guard: bool = Depends(require_dev_only),
) -> UserProfilePublic:
    """Apply a proposed profile delta after explicit user confirmation (UC §11.6).

    Proposals are EPHEMERAL — `delta_id` is generated by `preference_service` and never
    stored server-side, so the FE re-sends the delta body {field, operation, value} and
    the path `delta_id` is used only as an idempotency/correlation key (persisted in the
    event's `evidence_refs`). The service owns one DB tx: idempotent via
    `find_by_evidence(delta_id, "confirmed")`, upserts `user_profiles`, then appends a
    `preference_events` audit row (status=confirmed, scope=confirmed_global)."""
    _validate_delta(body)
    client_ip = request.client.host if request.client else "unknown"
    logger.info(
        "preference_confirm user_id=%s delta_id=%s op=%s field=%s ip=%s",
        user_id,
        delta_id,
        body.operation,
        body.field,
        client_ip,
    )
    # P1 TODO(AUTH): assert path user_id == authenticated principal before apply_delta
    # (IDOR). require_dev_only blocks production until real auth lands.
    return preference_confirm_service.confirm(user_id, delta_id, body)


@router.post("/{user_id}/profile/deltas/{delta_id}/reject")
def reject_delta(
    user_id: str,
    delta_id: str,
    request: Request,
    body: ConfirmDeltaRequest | None = None,
    _guard: bool = Depends(require_dev_only),
) -> dict[str, bool]:
    """Record an explicit rejection of a proposed delta (UC §11.6).

    No profile mutation; appends a `preference_events` audit row (status=rejected). ``body``
    is optional — the FE ``rejectDelta`` posts no body (the path carries user_id + delta_id);
    field/op are then logged as ``<none>``. When a body IS sent it is validated like confirm."""
    if body is not None:
        _validate_delta(body)
    client_ip = request.client.host if request.client else "unknown"
    logger.info(
        "preference_reject user_id=%s delta_id=%s op=%s field=%s ip=%s",
        user_id,
        delta_id,
        getattr(body, "operation", "<none>"),
        getattr(body, "field", "<none>"),
        client_ip,
    )
    # P1 TODO(AUTH): assert path user_id == authenticated principal (IDOR) — see confirm_delta.
    preference_confirm_service.reject(user_id, delta_id, body)
    return {"ok": True}


@router.post("/{user_id}/memory/clear", response_model=UserProfilePublic)
def clear_memory(
    user_id: str,
    request: Request,
    _guard: bool = Depends(require_dev_only),
) -> UserProfilePublic:
    """Clear remembered memory — context_memory notes (allergy/diet declarations) + the taste
    fields the constraint layer reads (dietary, liked/disliked cuisines, budget). The FE 'clear
    memory' test control resets the user to a clean slate. IDOR-guarded (dev-only until auth)."""
    client_ip = request.client.host if request.client else "unknown"
    logger.info("memory_clear user_id=%s ip=%s", user_id, client_ip)
    return user_profile_service.clear_memory(user_id)


class LikedMerchantRequest(BaseModel):
    """Body for POST /liked-merchants — a single merchant_id to like."""

    merchant_id: str


@router.get("/{user_id}/liked-merchants")
def list_liked_merchants(user_id: str) -> dict:
    """List the user's liked merchants (episodic memory) — newest-first.

    Read-only, not IDOR-guarded (the merchant list carries no PII; the FE loads its own user_id,
    same as GET /profile). Powers the FE heart-state + the agent's 'quán từng thích' recall."""
    return {"user_id": user_id, "liked_merchants": liked_merchant_service.list_liked(user_id)}


@router.post("/{user_id}/liked-merchants", status_code=201)
def like_merchant(
    user_id: str,
    body: LikedMerchantRequest,
    request: Request,
    _guard: bool = Depends(require_dev_only),
) -> dict:
    """Like a merchant (heart on the card) — durable episodic memory + audit log.

    Idempotent (re-liking is a no-op). 404 when the merchant_id is unknown (merchants FK).
    IDOR-guarded (dev-only until auth — matches PATCH /profile)."""
    client_ip = request.client.host if request.client else "unknown"
    logger.info("merchant_like user_id=%s merchant_id=%s ip=%s", user_id, body.merchant_id, client_ip)
    try:
        liked_merchant_service.like(user_id, body.merchant_id)
    except IntegrityError:
        raise HTTPException(status_code=404, detail=f"merchant not found: {body.merchant_id}")
    return {"ok": True, "merchant_id": body.merchant_id}


@router.delete("/{user_id}/liked-merchants/{merchant_id}")
def unlike_merchant(
    user_id: str,
    merchant_id: str,
    request: Request,
    _guard: bool = Depends(require_dev_only),
) -> dict:
    """Remove a like. Idempotent (no-op if not liked). IDOR-guarded."""
    client_ip = request.client.host if request.client else "unknown"
    logger.info("merchant_unlike user_id=%s merchant_id=%s ip=%s", user_id, merchant_id, client_ip)
    liked_merchant_service.unlike(user_id, merchant_id)
    return {"ok": True, "merchant_id": merchant_id}


@router.delete("/{user_id}/preferences/{field}")
def delete_preference(user_id: str, field: str) -> object:
    return not_implemented(f"DELETE /api/v1/users/{{user_id}}/preferences/{field}")


@router.get("/{user_id}/sessions")
def list_sessions(user_id: str) -> object:
    return not_implemented(f"GET /api/v1/users/{user_id}/sessions")
