"""FastAPI app factory — FROZEN (Phase 0 seam #4).

Do NOT edit this file in Phase 1/2. All base routers are already included (stub 501).
Each vertical implements its OWN router file; cross-cutting extensions attach via
`app/extensions.py` registries. main.py only assembles.
"""
from __future__ import annotations

import os
os.environ["CREWAI_TELEMETRY_OPT_OUT"] = "true"
os.environ["OTEL_SDK_DISABLED"] = "true"
os.environ["OTEL_TRACES_EXPORTER"] = "none"

from contextlib import asynccontextmanager

from fastapi import FastAPI

from app import extensions
from core.logging import configure_logging, get_logger
from core.settings import get_settings

# --- Base routers (frozen include list; owners edit only their own router file) ---
from routes import (
    customer_agent_routes,
    event_routes,
    health,
    map_routes,
    merchant_agent_routes,
    merchant_profile_routes,
    merchant_search_routes,
    trace_routes,
    user_routes,
)

logger = get_logger(__name__)

_BASE_ROUTERS = [
    health.router,
    merchant_search_routes.router,
    merchant_profile_routes.router,
    customer_agent_routes.router,
    merchant_agent_routes.router,
    user_routes.router,
    event_routes.router,
    map_routes.router,
    trace_routes.router,
]


@asynccontextmanager
async def lifespan(app: FastAPI):
    for hook in extensions.STARTUP_HOOKS:
        result = hook(app)
        if hasattr(result, "__await__"):
            await result
    logger.info("app_startup_complete")
    yield
    for hook in extensions.SHUTDOWN_HOOKS:
        result = hook(app)
        if hasattr(result, "__await__"):
            await result
    logger.info("app_shutdown_complete")


def create_app() -> FastAPI:
    configure_logging()
    settings = get_settings()
    app = FastAPI(title=settings.app_name, version="0.1.0", lifespan=lifespan)

    extensions.install_middleware(app)
    extensions.install_exception_handlers(app)

    for router in _BASE_ROUTERS:
        app.include_router(router)
    # Extra routers contributed by verticals via the extension seam.
    for router in extensions.ROUTERS:
        app.include_router(router)

    return app


app = create_app()
