"""create_initial_schema

Revision ID: 026b4a8e16d0
Revises: 
Create Date: 2026-07-20 11:40:33.682957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '026b4a8e16d0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cuisine', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('open_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('city_slug', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('is_demo_target', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('merchant_id')
    )
    op.create_table('user_profiles',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('liked_cuisines', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('disliked_cuisines', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('spice_tolerance', sa.String(), nullable=True),
    sa.Column('dietary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('budget_level', sa.String(), nullable=True),
    sa.Column('distance_preference_km', sa.Float(), nullable=True),
    sa.Column('current_lat', sa.Float(), nullable=True),
    sa.Column('current_lng', sa.Float(), nullable=True),
    sa.Column('location_updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('context_memory', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('interaction_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('chat_sessions',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('delivery_feedbacks',
    sa.Column('feedback_id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('driver_id', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_table('menu_items',
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('diet_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ingredient_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('taste_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_table('merchant_profiles',
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('dimensions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('merchant_id')
    )
    op.create_table('operational_metrics',
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('avg_prep_time_min', sa.Float(), nullable=True),
    sa.Column('peak_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('merchant_id')
    )
    op.create_table('reviews',
    sa.Column('review_id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('foody_restaurant_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('author_id', sa.String(), nullable=True),
    sa.Column('author_name', sa.String(), nullable=True),
    sa.Column('total_like', sa.Integer(), nullable=True),
    sa.Column('total_comment', sa.Integer(), nullable=True),
    sa.Column('total_pictures', sa.Integer(), nullable=True),
    sa.Column('review_url', sa.String(), nullable=True),
    sa.Column('source_page', sa.String(), nullable=True),
    sa.Column('comments_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_table('chat_messages',
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('sender', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('food_images',
    sa.Column('image_id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('dish_image_quality', sa.Float(), nullable=True),
    sa.Column('logo_quality', sa.Float(), nullable=True),
    sa.Column('blur_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['menu_items.item_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.merchant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_images')
    op.drop_table('chat_messages')
    op.drop_table('reviews')
    op.drop_table('operational_metrics')
    op.drop_table('merchant_profiles')
    op.drop_table('menu_items')
    op.drop_table('delivery_feedbacks')
    op.drop_table('chat_sessions')
    op.drop_table('user_profiles')
    op.drop_table('merchants')
    # ### end Alembic commands ###
